-- The schema the demo app is written against.
--
-- It is upstream's own migration for the todo list quickstart:
--
--   examples/todo-list/nextjs-todo-list/supabase/migrations/20230712094349_init.sql
--
-- The svelte app in app/ has no migration of its own. Its README tells
-- you to run the "TODO LIST" quickstart from the dashboard, which is
-- the same table and the same four policies.
--
-- Three differences from upstream, all of them so the file can be
-- applied twice to the same database and so there is no CLI in the
-- loop: the drop at the top, the policies created after the table
-- rather than with it, and the grants at the bottom. Supabase grants
-- the api roles on the public schema by default and zou does not, so
-- without them every request is a 42501 rather than an empty list.
--
-- auth.users has to exist before this runs. zou creates it on its
-- first connection to a database, which is why the harness warms the
-- server before it says it is ready.

drop table if exists public.todos;

create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  task text check (char_length(task) > 3),
  is_complete boolean default false,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table todos enable row level security;

create policy "Individuals can create todos." on todos for
    insert with check (auth.uid() = user_id);

create policy "Individuals can view their own todos. " on todos for
    select using (auth.uid() = user_id);

create policy "Individuals can update their own todos." on todos for
    update using (auth.uid() = user_id);

create policy "Individuals can delete their own todos." on todos for
    delete using (auth.uid() = user_id);

grant select, insert, update, delete on public.todos to anon, authenticated, service_role;

notify pgrst, 'reload schema';
